### ISSUE TITLE
Use of "chcp" not permitted under CGI for non-admin users

### ISSUE THREAD

**Issue by jimtut** [gisle/encode-locale#6]
I started a fairly detailed thread on StackOverflow for this problem: http://stackoverflow.com/questions/19772340/lwpuseragents-env-proxy-gives-access-is-denied-for-non-admin-users

Basically, Encode::Locale is used by LWP::UserAgent which is used by LWP::Simple, which I'm trying to use in a CGI script running under IIS with integrated Windows Authentication.  That means that the CGI runs as the user logged into IIS, most of whom are NOT admins on the webserver.

Encode::Locale's fallback to calling "chcp" (actually, like this: "qx(chcp)") results in an "Access is denied" error.  This is bad enough for Encode::Locale(), but if the CGI includes "use LWP::Simple;" (which is how my script was written), then the error happens at the beginning of the runtime (?), before any of the CGI can be setup, and the webpage user gets an error "The specified CGI application misbehaved by not returning a complete set of HTTP headers".

We need some workaround to NOT use "chcp" in environments like this.

**Comment by mohawk2** [comment]
@jimtut, I've just made a PR (#10) which I believe fixes this. Could you try the code there and see if it does?

**Comment by jimtut** [comment]
Yes, I just downloaded the code there, replaced the original Locale.pm file (rev 1.03), and this simple CGI script below is now working for admins and non-admins.  Thanks!

    #!perl
    use Encode;
    use Encode::Locale;
    print "Content-Type: text/plain\n\n";
    print(decode("locale", "abc"));
